export default [
  {
    path: 'course1-1',
    subTitle: 'course.menu1.title',
    title: 'course.menu1.menuChild.menuChild1',
    component: 'course1-1',
  },
  {
    path: 'course1-2',
    subTitle: 'course.menu1.title',
    title: 'course.menu1.menuChild.menuChild2',
    component: 'course1-2',
  },
  {
    path: 'course1-3',
    subTitle: 'course.menu1.title',
    title: 'course.menu1.menuChild.menuChild3',
    component: 'course1-3',
  },
  {
    path: 'course1-4',
    subTitle: 'course.menu1.title',
    title: 'course.menu1.menuChild.menuChild4',
    component: 'course1-4',
  },
  {
    path: 'course2-1',
    subTitle: 'course.menu2.title',
    title: 'course.menu2.menuChild.menuChild1',
    component: 'course2-1',
  },
  {
    path: 'course2-2',
    subTitle: 'course.menu2.title',
    title: 'course.menu2.menuChild.menuChild2',
    component: 'course2-2',
  },
  {
    path: 'course2-3',
    subTitle: 'course.menu2.title',
    title: 'course.menu2.menuChild.menuChild3',
    component: 'course2-3',
  },
  {
    path: 'course3-1',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild1',
    component: 'course3-1',
  },
  {
    path: 'course3-2',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild2',
    component: 'course3-2',
  },
  {
    path: 'course3-3',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild3',
    component: 'course3-3',
  },
  {
    path: 'course3-4',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild4',
    component: 'course3-4',
  },
  {
    path: 'course3-5',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild5',
    component: 'course3-5',
  },
  {
    path: 'course3-6',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild6',
    component: 'course3-6',
  },
  {
    path: 'course3-7',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild7',
    component: 'course3-7',
  },
  {
    path: 'course3-8',
    subTitle: 'course.menu3.title',
    title: 'course.menu3.menuChild.menuChild8',
    component: 'course3-8',
  },
  {
    path: 'course4-1',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild1',
    component: 'course4-1',
  },
  {
    path: 'course4-2',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild2',
    component: 'course4-2',
  },
  {
    path: 'course4-3',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild3',
    component: 'course4-3',
  },
  {
    path: 'course4-4',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild4',
    component: 'course4-4',
  },
  {
    path: 'course4-5',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild5',
    component: 'course4-5',
  },
  {
    path: 'course4-6',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild6',
    component: 'course4-6',
  },
  {
    path: 'course4-7',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild7',
    component: 'course4-7',
  },
  {
    path: 'course4-8',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild8',
    component: 'course4-8',
  },
  {
    path: 'course4-9',
    subTitle: 'course.menu4.title',
    title: 'course.menu4.menuChild.menuChild9',
    component: 'course4-9',
  },
  {
    path: 'course5-1',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild1',
    component: 'course5-1',
  },
  {
    path: 'course5-2',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild2',
    component: 'course5-2',
  },
  {
    path: 'course5-3',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild3',
    component: 'course5-3',
  },
  {
    path: 'course5-4',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild4',
    component: 'course5-4',
  },
  {
    path: 'course5-5',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild5',
    component: 'course5-5',
  },
  {
    path: 'course5-6',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild6',
    component: 'course5-6',
  },
  {
    path: 'course5-7',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild7',
    component: 'course5-7',
  },
  {
    path: 'course5-8',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild8',
    component: 'course5-8',
  },
  {
    path: 'course5-9',
    subTitle: 'course.menu5.title',
    title: 'course.menu5.menuChild.menuChild9',
    component: 'course5-9',
  },
  {
    path: 'course6-1',
    subTitle: 'course.menu6.title',
    title: 'course.menu6.menuChild.menuChild1',
    component: 'course6-1',
  },
  {
    path: 'course6-2',
    subTitle: 'course.menu6.title',
    title: 'course.menu6.menuChild.menuChild2',
    component: 'course6-2',
  },
  {
    path: 'course6-3',
    subTitle: 'course.menu6.title',
    title: 'course.menu6.menuChild.menuChild3',
    component: 'course6-3',
  },
  {
    path: 'course6-4',
    subTitle: 'course.menu6.title',
    title: 'course.menu6.menuChild.menuChild4',
    component: 'course6-4',
  },
  {
    path: 'course6-5',
    subTitle: 'course.menu6.title',
    title: 'course.menu6.menuChild.menuChild5',
    component: 'course6-5',
  },
  {
    path: 'course7-1',
    subTitle: 'course.menu7.title',
    title: 'course.menu7.menuChild.menuChild1',
    component: 'course7-1',
  },
  {
    path: 'course7-2',
    subTitle: 'course.menu7.title',
    title: 'course.menu7.menuChild.menuChild2',
    component: 'course7-2',
  },
  {
    path: 'course7-3',
    subTitle: 'course.menu7.title',
    title: 'course.menu7.menuChild.menuChild3',
    component: 'course7-3',
  },
  {
    path: 'course7-4',
    subTitle: 'course.menu7.title',
    title: 'course.menu7.menuChild.menuChild4',
    component: 'course7-4',
  },
  {
    path: 'course7-5',
    subTitle: 'course.menu7.title',
    title: 'course.menu7.menuChild.menuChild5',
    component: 'course7-5',
  },
  {
    path: 'course7-6',
    subTitle: 'course.menu7.title',
    title: 'course.menu7.menuChild.menuChild6',
    component: 'course7-6',
  },
  {
    path: 'course7-7',
    subTitle: 'course.menu7.title',
    title: 'course.menu7.menuChild.menuChild7',
    component: 'course7-7',
  },
];
